name: Build TapokAntivirus v3.1
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        # Сборка с поддержкой GUI и скрытием консоли
        # --collect-all подтягивает скрытые зависимости библиотек
        pyinstaller --noconsole --onefile --icon="icon.ico" `
        --name "TapokAntivirus_Setup" `
        --collect-all tkinter `
        --collect-all PIL `
        main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tapok_Final_Build
        path: dist/TapokAntivirus_Setup.exe
        retention-days: 5
        
